// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace ICT4EVENTUnitTest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// LogIn - Use 'LogInParams' to pass parameters into this method.
        /// </summary>
        public void LogIn()
        {
            #region Variable Declarations
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            WinEdit uITxtUserNameEdit = this.UILoginScreenWindow.UITxtUserNameWindow.UITxtUserNameEdit;
            WinEdit uITxtPasswordEdit = this.UILoginScreenWindow.UITxtPasswordWindow.UITxtPasswordEdit;
            WinButton uILoginButton = this.UILoginScreenWindow.UILoginWindow.UILoginButton;
            WinButton uIItemButton = this.UILoginScreenWindow.UIItemWindow.UIItemButton;
            #endregion

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(23, 5));

            // Type 'admin' in 'txtUserName' text box
            uITxtUserNameEdit.Text = this.LogInParams.UITxtUserNameEditText;

            // Type '{Tab}' in 'txtUserName' text box
            Keyboard.SendKeys(uITxtUserNameEdit, this.LogInParams.UITxtUserNameEditSendKeys, ModifierKeys.None);

            // Type '********' in 'txtPassword' text box
            Keyboard.SendKeys(uITxtPasswordEdit, this.LogInParams.UITxtPasswordEditSendKeys, true);

            // Click 'Login' button
            Mouse.Click(uILoginButton, new Point(9, 20));

            // Click '>' button
            Mouse.Click(uIItemButton, new Point(17, 7));
        }
        
        #region Properties
        public virtual LogInParams LogInParams
        {
            get
            {
                if ((this.mLogInParams == null))
                {
                    this.mLogInParams = new LogInParams();
                }
                return this.mLogInParams;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow();
                }
                return this.mUIOKWindow;
            }
        }
        
        public UILoginScreenWindow UILoginScreenWindow
        {
            get
            {
                if ((this.mUILoginScreenWindow == null))
                {
                    this.mUILoginScreenWindow = new UILoginScreenWindow();
                }
                return this.mUILoginScreenWindow;
            }
        }
        #endregion
        
        #region Fields
        private LogInParams mLogInParams;
        
        private UIOKWindow mUIOKWindow;
        
        private UILoginScreenWindow mUILoginScreenWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LogIn'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class LogInParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'admin' in 'txtUserName' text box
        /// </summary>
        public string UITxtUserNameEditText = "admin";
        
        /// <summary>
        /// Type '{Tab}' in 'txtUserName' text box
        /// </summary>
        public string UITxtUserNameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'txtPassword' text box
        /// </summary>
        public string UITxtPasswordEditSendKeys = "ltMtR4VOfdZS3D8xaljxesqUwEXKaQEX";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "OK";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
            this.WindowTitles.Add("OK");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("OK");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UILoginScreenWindow : WinWindow
    {
        
        public UILoginScreenWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "LoginScreen";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("LoginScreen");
            #endregion
        }
        
        #region Properties
        public UITxtUserNameWindow UITxtUserNameWindow
        {
            get
            {
                if ((this.mUITxtUserNameWindow == null))
                {
                    this.mUITxtUserNameWindow = new UITxtUserNameWindow(this);
                }
                return this.mUITxtUserNameWindow;
            }
        }
        
        public UITxtPasswordWindow UITxtPasswordWindow
        {
            get
            {
                if ((this.mUITxtPasswordWindow == null))
                {
                    this.mUITxtPasswordWindow = new UITxtPasswordWindow(this);
                }
                return this.mUITxtPasswordWindow;
            }
        }
        
        public UILoginWindow UILoginWindow
        {
            get
            {
                if ((this.mUILoginWindow == null))
                {
                    this.mUILoginWindow = new UILoginWindow(this);
                }
                return this.mUILoginWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UITxtUserNameWindow mUITxtUserNameWindow;
        
        private UITxtPasswordWindow mUITxtPasswordWindow;
        
        private UILoginWindow mUILoginWindow;
        
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITxtUserNameWindow : WinWindow
    {
        
        public UITxtUserNameWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtUserName";
            this.WindowTitles.Add("LoginScreen");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtUserNameEdit
        {
            get
            {
                if ((this.mUITxtUserNameEdit == null))
                {
                    this.mUITxtUserNameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtUserNameEdit.WindowTitles.Add("LoginScreen");
                    #endregion
                }
                return this.mUITxtUserNameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtUserNameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITxtPasswordWindow : WinWindow
    {
        
        public UITxtPasswordWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtPassword";
            this.WindowTitles.Add("LoginScreen");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtPasswordEdit
        {
            get
            {
                if ((this.mUITxtPasswordEdit == null))
                {
                    this.mUITxtPasswordEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtPasswordEdit.WindowTitles.Add("LoginScreen");
                    #endregion
                }
                return this.mUITxtPasswordEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtPasswordEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UILoginWindow : WinWindow
    {
        
        public UILoginWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnLogin";
            this.WindowTitles.Add("LoginScreen");
            #endregion
        }
        
        #region Properties
        public WinButton UILoginButton
        {
            get
            {
                if ((this.mUILoginButton == null))
                {
                    this.mUILoginButton = new WinButton(this);
                    #region Search Criteria
                    this.mUILoginButton.SearchProperties[WinButton.PropertyNames.Name] = "Login";
                    this.mUILoginButton.WindowTitles.Add("LoginScreen");
                    #endregion
                }
                return this.mUILoginButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUILoginButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnGO";
            this.WindowTitles.Add("LoginScreen");
            #endregion
        }
        
        #region Properties
        public WinButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIItemButton.SearchProperties[WinButton.PropertyNames.Name] = ">";
                    this.mUIItemButton.WindowTitles.Add("LoginScreen");
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIItemButton;
        #endregion
    }
}
